server:
  port: 8081
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/ms-email
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: **********
    port: 587
    username: **********
    password: **********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
