server:
  port: 8081
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/ms-email
  data:
    mongodb:
      database: ms-email
      uri: mongodb://mongoadmin:admin@localhost:27017
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://nblxxobk:1WzX3eDk6aF0x-q7QS_EU3jWTPgzoK5f@jackal.rmq.cloudamqp.com/nblxxobk
    queue: ms-email

  mail:
    host: email-smtp.sa-east-1.amazonaws.com
    port: 587
    username: AKIAWTKIPISH7MJH72HB
    password: BO33MQd4PLgBaDPfgq6XfadqTUEKNP7A7CL7BB6WeiSH
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
